CREATE TABLE IF NOT EXISTS account_type (
    id BIGSERIAL PRIMARY KEY,
    label VARCHAR(500) NOT NULL,
    description VARCHAR(2000) NOT NULL
);

CREATE TABLE IF NOT EXISTS account (
    id BIGSERIAL PRIMARY KEY,
    account_name VARCHAR(500) NOT NULL,
    account_type_id BIGINT NOT NULL
);