services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: vihaan
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: finance_db
    ports:
      - "5433:5432"
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data